INSERT INTO Products ( Name, Price, Material, MadeIn, CreateDate, Gender, Detail, BrandId, CategoryId, SubCategoryId) VALUES
( N'Đồng Hồ Đôi Citizen AU1062-56E - GA1052-55E', 20, N'Mạ Vàng', N'Nhật Bản','20220501 10:00:09 AM', 2, N'Đồng Hồ Đôi Citizen AU1062-56E - GA1052-55E có thiết kế sang trọng với 2 tông màu quyền lực: đen - vàng. Mặt số trơn với nền mặt đen, nổi bật là 2 kim mảnh, dây đồng hồ Citizen mạ vàng.', 94, 1, 3),
( N'Đồng Hồ Đôi Citizen BM7344-54E - EW2394-59E', 10, N'Thép không gỉ 316L', N'Nhật Bản','20220501 10:00:09 AM', 2, N'Đồng Hồ Đôi Citizen BM7344-54E - EW2394-59E từ thương hiệu Citizen với thiết kế theo phong cách đơn giản nhưng sang trọng. Mặt số tối giản với nền mặt đen, thiết kế 3 kim và nhấn nhá bởi những cọc số đính đá kết hợp cùng dây đồng hồ demi vàng - bạc trẻ trung.', 94, 1, 3),
( N'Đồng Hồ Orient Esteem Gen 2 FAG02003W0 ', 15, N'Thép không gỉ 316L', N'Nhật Bản','20220501 10:00:09 AM', 1, N'Orient Esteem 2 FAG02003W0 thuộc bộ sưu tập Classic của hãng Orient danh tiếng. Với thiết kệ lộ cơ độc đáo, mặt số đơn giản với các chi tiết sắc nét, tinh tế kết hợp cùng dây da nâu vân cá sấu có phần cổ điển tạo vẻ ngoài lịch lãm cho các quý ông. Đường kính mặt 41mm, độ dày vỏ 11mm phù hợp với mọi kích thước cố tay nam giới.', 315, 1, 1),
( N'Đồng Hồ Lộ Cơ Seiko SSA231K1', 15, N'Hardlex', N'Nhật Bản','20220501 10:00:09 AM', 1, N'Đồng hồ Seiko SSA231K1 dây da màu nâu là chiếc đồng hồ nam cao cấp có thiết kế lộ máy độc đáo kết hợp với sự cổ điển, sang trọng tới từ thương hiệu Seiko Nhật Bản.', 365, 1, 1),
( N'Đồng Hồ Rolex Datejust Stainless Steel And Yellow Gold Mop Dial 278273-0028 Màu Xám Vàng', 20, N'Thép không gỉ/Vàng 18k', N'Thụy Sỹ','20220501 10:00:09 AM', 1, N'Đồng Hồ Rolex Datejust Stainless Steel And Yellow Gold Mop Dial 278273-0028 Màu Xám Vàng là chiếc đồng hồ cao cấp được nhiều tín đồ thời trang quan tâm hiện nay. Sở hữu thiết kế hiện đại, cùng gam màu sang trọng, Rolex Datejust Stainless Steel And Yellow Gold Mop Dial 278273-0028 khi đeo lên tay sẽ vô cùng lịch lãm và đẳng cấp.', 338, 1, 1),
( N'Đồng Hồ Nam Rolex Datejust 36  Màu Xám Mặt Trắng', 20, N'Thép không gỉ/Vàng 18k', N'Thụy Sỹ','20220501 10:00:09 AM', 1, N'Đồng Hồ Nam Rolex Datejust 36 126200-0007 Màu Xám Mặt Trắng là chiếc đồng hồ cao cấp được nhiều tín đồ thời trang quan tâm hiện nay. Sở hữu thiết kế hiện đại, cùng gam màu sang trọng, Rolex Datejust 36 126200-0007 khi đeo lên tay sẽ vô cùng lịch lãm và đẳng cấp.', 338, 1, 1),
( N'Đồng Hồ Nam Casio MTP-1374D-1AV Màu Trắng', 15, N'Thép không gỉ', N'Nhật Bản','20220501 10:00:09 AM', 1, N'Đồng Hồ Nam Casio MTP-1374D-1AV Màu Trắng là chiếc đồng hồ nam cao cấp vừa mới ra mắt của nhà Casio. Sở hữu thiết kế hiện đại cùng gam màu sang trọng, ngay từ khi có mặt trên thị trường Casio MTP-1374D-1AV được nhiều tín đồ thời trang săn đón.', 110, 1, 1),
( N'Đồng Hồ Omega De Ville Ladymatic', 20, N'Thép không gỉ', N'Thụy Sĩ','20220501 10:00:09 AM', 0, N'Đồng hồ Omega De Ville Ladymatic 425.38.34.20.55.001 có bộ máy tự động Co-Axial calibre 8520 đem tới khả năng trữ cót lên tới 50 giờ đồng hồ.', 314, 1, 1),
( N'Đồng Hồ Omega Ladymatic Co‑Axial', 18, N'Thép không gỉ', N'Thụy Sĩ','20220501 10:00:09 AM', 0, N'Đồng hồ Omega Ladymatic Co‑Axial 425.63.34.20.51.001 là chiếc đồng hồ cao cấp được nhiều tín đồ thời trang quan tâm hiện nay. Sở hữu thiết kế hiện đại, cùng gam màu sang trọng Omega Ladymatic Co‑Axial 425.63.34.20.51.001 khi đeo lên tay sẽ vô cùng lịch lãm và đẳng cấp.', 314, 1, 1),
( N'Đồng Hồ Nữ Omega De Ville Ladymat', 20, N'Thép không gỉ', N'Thụy Sĩ','20220501 10:00:09 AM', 0, N'Đồng Hồ Nữ Omega De Ville Ladymat 425.63.34.20.51.002 là chiếc đồng hồ cao cấp được nhiều tín đồ thời trang quan tâm hiện nay. Sở hữu thiết kế hiện đại, cùng gam màu sang trọng Omega De Ville Ladymat 425.63.34.20.51.002 khi đeo lên tay sẽ vô cùng lịch lãm và đẳng cấp.', 314, 1, 1),
( N'Đồng Hồ Burgi BUR154BG Cho Nữ', 20, N'Thép không gỉ', N'Mỹ','20220501 10:00:09 AM', 0, N'Đồng hồ Burgi BUR154BG là chiếc đồng hồ từ thương hiệu Burgi có thiết kế dây da, bezel được đính đá sang trọng tạo nên tổng thể hoàn hảo, tôn lên vẻ ngoài đầy sức hút của các cô gái.', 42, 1, 1),
( N'Đồng Hồ Burgi BUR128BU Cho Nữ', 15, N'Thép không gỉ', N'Mỹ','20220501 10:00:09 AM', 0, N'Đồng hồ Burgi BUR128BU  là chiếc đồng hồ từ thương hiệu Burgi có thiết kế dây da, bezel được đính đá sang trọng tạo nên tổng thể hoàn hảo, tôn lên vẻ ngoài đầy sức hút của các cô gái.', 42, 1, 1),
( N'Đồng Hồ Burgi BUR126YG Mạ Vàng Cho Nữ', 15, N'Mỹ', N'Thụy Sĩ','20220501 10:00:09 AM', 0, N'Đồng hồ Burgi BUR126YG được thiết kế mạ vàng sang trọng kết hợp với vòng bezel đính hàng trăm viên đá tinh xảo, dây đồng hồ trẻ trung tạo tổng thể chiếc đồng hồ Burgi hoàn hảo.', 42, 1, 1),
( N'Đồng Hồ Nữ Hublot Big Bang One Click Gold Diamond Pave 33 485.OX.1180.RX.1604', 25, N'Sapphire', N'Thụy Sĩ','20220501 10:00:09 AM', 0, N'Đồng Hồ Nữ Hublot Big Bang One Click Gold Diamond Pave 33 485.OX.1180.RX.1604 là chiếc đồng hồ cao cấp được nhiều tín đồ thời trang quan tâm hiện nay. Sở hữu thiết kế hiện đại, cùng gam màu sang trọng Hublot Big Bang One Click Gold Diamond Pave 33 485.OX.1180.RX.1604  khi đeo lên tay sẽ vô cùng sang trọng và đẳng cấp.', 211, 1, 1),
( N'Đồng Hồ Versace Womens Revive Black Enamel Dial Leather 36 Diamonds Watch VAI060016 35mm', 25, N'Sapphire', N'Ý','20220501 10:00:09 AM', 0, N'Được giới thiệu cách đây không lâu, Đồng Hồ Versace Womens Revive Black Enamel Dial Leather 36 Diamonds Watch VAI060016 35mm đích thị trở thành xu hướng đồng hồ nữ cao cấp được rất nhiều tín đồ thời trang khao khát bởi vẻ ngoài sang trọng, nữ tính dành cho những người phụ nữ thành đạt.', 394, 1, 1),
( N'Đồng Hồ Zenith El Primero Synopsis 03.2170.4613/21.C714 Màu Đen', 15, N'Thép không gỉ ', N'Thụy sỹ','20220501 10:00:09 AM', 0, N'Đồng Hồ Zenith El Primero Synopsis 03.2170.4613/21.C714 Màu Đen là chiếc đồng hồ cao cấp đến từ thương hiệu Zenith nổi tiếng. Sở hữu gam màu thanh lịch cùng thiết kế hiện đại, Zenith El Primero Synopsis 03.2170.4613/21.C714 cho người đeo thêm sang trọng, đẳng cấp hơn.', 413, 1, 1),
( N'Đồng Hồ Zenith El Primero Synopsis 03.2170.4613/01.M2170 Màu Bạc', 17, N'Thép không gỉ ', N'Thụy sỹ','20220501 10:00:09 AM', 1, N'Đồng Hồ Zenith El Primero Synopsis 03.2170.4613/01.M2170 Màu Bạc là chiếc đồng hồ cao cấp đến từ thương hiệu Zenith nổi tiếng. Sở hữu gam màu thanh lịch cùng thiết kế hiện đại, Zenith El Primero Synopsis 03.2170.4613/01.M2170 cho người đeo thêm sang trọng, đẳng cấp hơn.', 413, 1, 1),
( N'Đồng Hồ Zenith Elite Ultra Thin Lady 03.2310.679/38.M2310 Màu Bạc', 19, N'Thép không gỉ ', N'Thụy sỹ','20220501 10:00:09 AM', 0, N'Đồng Hồ Zenith Elite Ultra Thin Lady 03.2310.679/38.M2310 Màu Bạc là chiếc đồng hồ cao cấp đến từ thương hiệu Zenith nổi tiếng. Sở hữu gam màu thanh lịch cùng thiết kế hiện đại, Zenith Elite Ultra Thin Lady 03.2310.679/38.M2310 cho người đeo thêm sang trọng, đẳng cấp hơn.', 413, 1, 1),

INSERT INTO Products ( Name, Price, Material, MadeIn, CreateDate, Gender, Detail, BrandId, CategoryId, SubCategoryId) VALUES
( N'Ví Nam Tommy Hilfiger Mens Ranger Passcase Brown 5673/02 Màu Nâu', 10, N'Da ', N'Mỹ','20220501 10:00:09 AM', 1, N'Ví Tommy Hilfiger Mens Ranger Passcase Brown 5673/02 Màu Nâu là chiếc ví nam cao cấp được thiết kế đẹp mắt, thời trang đến từ thương hiệu Tommy Hilfiger của Mỹ. Sản phẩm làm bằng da cao cấp, bền đẹp trong suốt quá trình sử dụng.', 375, 2, 12),
( N'Ví Nam Tommy Hilfiger Men Thin Sleek Casual Bifold Wallet ', 10, N'Da ', N'Mỹ','20220501 10:00:09 AM', 1, N'Ví Nam Tommy Hilfiger Mens Thin Sleek Casual Bifold Wallet with 6 Credit Card Pockets And Removable Id Window là chiếc ví nam cao cấp được thiết kế đẹp mắt này sẽ là món quà hoàn hảo cho bạn.', 375, 2, 12),
( N'Túi Đeo Vai Charles & Keith Chain Strap Shoulder Bag CK2-20840317-8 Màu Đen', 10, N'Da nhân tạo', N'Singapore','20220501 10:00:09 AM', 0, N'Túi Đeo Vai Charles & Keith Chain Strap Shoulder Bag CK2-20840317-8 Màu Đen chiếc túi xách nữ cao cấp được thiết kế kiểu dáng trẻ trung, hiện đại đến từ thương hiệu Charles & Keith nổi tiếng của Singapore. Túi Charles & Keith được làm từ chất liệu cao cấp bền đẹp trong suốt quá trình sử dụng.', 103, 2, 15),
( N'Túi Xách Charles & Keith Scarf-Wrapped Top Handle Bag Màu Đen', 14, N'Da nhân tạo', N'Singapore','20220501 10:00:09 AM', 0, N'Túi Xách Charles & Keith Scarf-Wrapped Top Handle Bag Màu Đen là chiếc túi xách nữ sang trọng, được thiết kế hiện đại đến từ thương hiệu Charles & Keith nổi tiếng của nước Singapore. Túi C&K này được làm từ chất liệu cao cấp bền đẹp trong suốt quá trình sử dụng.', 103, 2, 15),
( N'Túi Đeo Hông Adidas Waist Bag Black FN0890 Màu Đen', 8, N'Polyester', N'Đức','20220501 10:00:09 AM', 0, N'Túi Đeo Hông Adidas Waist Bag Black FN0890 Màu Đen là chiếc túi cao cấp được thiết kế trẻ trung năng động đến từ thương hiệu Adidas nổi tiếng của Đức. Sở hữu gam màu thanh lịch cùng chất liệu cao cấp, túi Adidas Waist Bag Black FN0890 cho người đeo thêm sành điệu hơn.', 33, 2, 16),
( N'Ví Furla 1927 Continental Bi-fold Textured Leather Wallet - Candy Rose PCV0ACO-ARE-1BR Màu Hồng', 10, N'Da ', N'Mỹ','20220501 10:00:09 AM', 0, N'Ví Furla 1927 Continental Bi-fold Textured Leather Wallet - Candy Rose PCV0ACO-ARE-1BR Màu Hồng là chiếc ví nữ sang trọng đến từ thương hiệu Furla nổi tiếng của Ý. được thiết kế trẻ trung hiện đại. Sản phẩm được làm từ chất liệu da nhân tạo cao cấp bền đẹp trong suốt thời gian sử dụng.', 167, 2, 12),
( N'Ví Furla Babylon S Textured Leather Bi-Fold Wallet - Camelia E PZ28 978876 Màu Hồng', 10, N'Da ', N'Ý','20220501 10:00:09 AM', 0, N'Ví Furla Babylon S Textured Leather Bi-Fold Wallet - Camelia E PZ28 978876 Màu Hồng là chiếc ví nữ sang trọng đến từ thương hiệu Furla nổi tiếng của Ý. Sản phẩm được làm từ chất liệu da nhân tạo cao cấp bền đẹp trong suốt thời gian sử dụng.', 167, 2, 12),
( N'Túi Đeo Chéo Coach Mini Lillie Caryall Màu Beige', 15, N'Canvas, Da ', N'Mỹ','20220501 10:00:09 AM', 0, N'Túi Đeo Chéo Coach Mini Lillie Caryall Màu Beige là chiếc túi xách dành cho nữ đến từ thương hiệu Coach nổi tiếng. Sở hữu thiết kế đẹp mắt cùng gam màu nổi bật, chiếc túi xách cho người dùng thêm sành điệu và sang trọng hơn khi mang bên mình.', 86, 2, 5),
( N'Túi Đeo Chéo Coach Mini Lillie Caryall Màu Nâu Đỏ', 15, N'Canvas, Da ', N'Mỹ','20220501 10:00:09 AM', 0, N'Túi Đeo Chéo Coach Mini Lillie Caryall Màu Nâu Đỏ là chiếc túi xách dành cho nữ đến từ thương hiệu Coach nổi tiếng. Sở hữu thiết kế đẹp mắt cùng gam màu nổi bật, chiếc túi xách cho người dùng thêm sành điệu và sang trọng hơn khi mang bên mình.', 86, 2, 5),
( N'Túi Đeo Chéo Michael Kors Lita Medium Two-Tone Logo Crossbody Bag Ballet Màu Hồng Phấn', 15, N'Vải cao cấp', N'Mỹ','20220501 10:00:09 AM', 0, N'Túi Đeo Chéo Michael Kors Lita Medium Two-Tone Logo Crossbody Bag Ballet 35T0GXPL2B Màu Hồng Phấn là chiếc túi xách cao cấp dành cho nữ đến từ thương hiệu Michael Kors. Sở hữu gam màu xinh xắn cùng chất liệu cao cấp, chiếc túi Túi Đeo Chéo Medium Two-Tone Logo Crossbody Bag Ballet đã thực sự thu hút sự săn đón của mọi khách hàng, nhất là những khách hàng khó tính.', 86, 2, 5),
( N'Túi Cầm Tay Versace Handbag Versace Jeans Couture 72VA4BF2 71578 003 Màu Trắng', 15, N'Vải cao cấp', N'Ý','20220501 10:00:09 AM', 0, N'Túi Cầm Tay Versace Handbag Versace Jeans Couture 72VA4BF2 71578 003 Màu Trắng là chiếc túi xách dành cho nữ đến từ thương hiệu Versace nổi tiếng của Ý. Chiếc túi Versace Handbag Versace Jeans Couture 72VA4BF2 71578 003  này thiết kế hiện đại, đa năng và hoàn toàn theo xu hướng thời thượng.', 394, 2, 8),
( N'Túi Cầm Tay Louis Vuitton Poche Toilette Nm Toiletry Bag M46037 Màu Nâu', 15, N'Canvas, Da', N'Pháp','20220501 10:00:09 AM', 0, N'Túi Cầm Tay Louis Vuitton Poche Toilette Nm Toiletry Bag M46037 Màu Nâu được thiết kế mang hơi hướng hiện đại, vừa đơn giản, vừa sang trọng. Túi được làm từ chất liệu cao cấp bền đẹp trong suốt quá trình sử dụng.', 264, 2, 8),

INSERT INTO Products ( Name, Price, Material, MadeIn, CreateDate, Gender, Detail, BrandId, CategoryId, SubCategoryId) VALUES
( N'Nước Hoa Nam Versace Eros Man EDT 5ml', 17, N'null', N'Pháp','20220501 10:00:09 AM', 1, N'Nước Hoa Versace Eros 5ml Nam là chai nước hoa Nam nguồn cảm hứng từ vị thần tình yêu trong thần thoại Hy Lạp. Chai Versace Eros 5ml cho nam là biểu tượng cho thần tình yêu Hy Lạp, đại diện của tình yêu, là trung tâm của các hương thơm, là sự kết hợp và thể hiện của niềm đam mê vô tận và ham muốn mãnh liệt.', 394, 3, 24),
( N'Nước Hoa Nam Versace Pour Homme EDT, 100ml', 17, N'null', N'Pháp','20220501 10:00:09 AM', 1, N'Nước hoa Versace Pour Homme 100ml là chai nước hoa Nam cá tính tới từ thương hiệu Versace Ý. Versace Pour Homme mang hương thơm đầy nam tính, mạnh mẽ liên kết sức mạnh và sự say mê để tạo nên một người đàn ông năng động và thành đạt.', 394, 3, 24),
( N'Nước Hoa Nam Armaf Club De Nuit Intense For Man, 105ml', 17, N'null', N'Ả Rập','20220501 10:00:09 AM', 1, N'Nước hoa Armaf Club De Nuit Intense For Man 105ml là chai nước hoa dành cho nam huyền bí đầy mạnh mẽ cá tính từ hãng Armaf Ả Rập. Armaf Club De Nuit Intense biến một chàng trai trở nên cuốn hút bằng sự tươi mới, trẻ trung và gần gũi kể cả ngay lần gặp đầu tiên bằng hương vị trái cây thuần khiết, dân giã.', 7, 3, 24),
( N'Nước Hoa Nam Afnan Supremacy Silver EDP 100ml', 15, N'null', N'Ả Rập','20220501 10:00:09 AM', 1, N'Nước Hoa Afnan Supremacy Silver EDP 100ml là chai nước hoa nam đến từ thương hiệu nổi tiếng Afnan Perfumes. Afnan Supremacy Silver mang đến nguồn sinh lực cho nam giới, một chai nước hoa mang hương tinh tế, nam tính, hấp dẫn.',31, 3, 24),
( N'Nước Hoa Nữ Burberry My Burberry EDP Mini 5ml', 15, N'null', N'Anh','20220501 10:00:09 AM', 0, N'Nước Hoa Nữ Burberry My Burberry EDP Mini 5ml là chai nước hoa nữ sang trọng đến từ thương hiệu nước hoa Burberry nổi tiếng Anh Quốc. Sản phẩm sở hữu mùi hương mang đến sự sang trọng, thanh lịch nhờ những hương thơm được hòa quyện phong phú.',43, 3, 24),
( N'Nước Hoa Nam Mini Jean Paul Gaultier Le Male EDT 7ml', 20, N'null', N'Pháp','20220501 10:00:09 AM', 0, N'Nước Hoa Nam Mini Jean Paul Gaultier Le Male EDT 7ml là chai nước hoa nam nhập khẩu, đến từ thương hiệu Jean Paul Gaultier của Pháp. Đây là chai nước hoa có mùi hương sâu lắng và ấm áp rất được yêu thích hiện nay.',245, 3, 24),
( N'Nước Hoa Kilian Kologne Shield Of Protection 50ml', 25, N'null', N'Pháp','20220501 10:00:09 AM', 2, N'Nước Hoa Kilian Kologne Shield Of Protection 50ml - là dòng nước hoa cao cấp của hương hiệu nước hoa nổi tiếng của Pháp By Kilian đã phát hành một hương thơm unisex mới Kologne Shield Of Protection từ bộ sưu tập The Fresh.',251, 3, 24),
( N'Nước Hoa Burberry My Burberry Blush EDP Cho Nữ 30ml', 15, N'null', N'Anh','20220501 10:00:09 AM', 0, N'Nước Hoa Burberry My Burberry Blush EDP 30ml là chai nước hoa nữ sang trọng đến từ thương hiệu nước hoa Burberry nổi tiếng Anh Quốc. Burberry My Burberry Blush sở hữu mùi hương mang đến sự sang trọng, thanh lịch nhờ những hương thơm được hòa quyện phong phú.',43, 3, 24),
( N'Nước Hoa Nam Cristiano Ronaldo CR7 Play It Cool 100ml', 25, N'null', N'Bồ Đào Nha','20220501 10:00:09 AM', 1, N'Nước Hoa Nam Cristiano Ronaldo CR7 Play It Cool 100ml là dòng nước hoa cao cấp đến từ thương hiệu Cristiano Ronaldo nổi tiếng của Bồ Đào Nha.Ngay từ khi có mặt trên thị trường cho đến nay, sản phẩm luôn nhận được sự săn đón nhiệt tình từ phái mạnh. ',77, 3, 24),
( N'Nước Hoa Nam Cristiano Ronaldo CR7 Game On 100ml', 25, N'null', N'Bồ Đào Nha','20220501 10:00:09 AM', 1, N'Nước Hoa Nam Cristiano Ronaldo CR7 Game On 100ml  là dòng nước hoa cao cấp đến từ thương hiệu Cristiano Ronaldo nổi tiếng của Bồ Đào Nha.Ngay từ khi có mặt trên thị trường cho đến nay, sản phẩm luôn nhận được sự săn đón nhiệt tình từ phái mạnh. ',77, 3, 24),
( N'Serum Biologique Recherche Collagene Marin Hỗ Trợ Dưỡng Ẩm, Săn Chắc Da 30ml', 17, N'null', N'Pháp','20220501 10:00:09 AM', 2, N'Serum Biologique Recherche Collagene Marin Hỗ Trợ Dưỡng Ẩm, Săn Chắc Da 30ml là dòng sản phẩm đến từ thương hiệu Biologique Recherche nổi tiếng của Pháp. Với thành phần giàu dưỡng chất Serum Biologique Recherche Collagene Marin hỗ trợ cải thiện độ căng và săn chắc của làn da giúp cho làn da trở nên mịn màng và đều màu hơn. ',59, 4, 26),
( N'Serum Biologique Recherche Hỗ Trợ Tái Tạo Da - VG Tensil 30ml', 17, N'null', N'Pháp','20220501 10:00:09 AM', 2, N'Serum Biologique Recherche Hỗ Trợ Tái Tạo Da - VG Tensil 30ml là dòng sản phẩm đến từ thương hiệu Biologique Recherche nổi tiếng của Pháp. Với thành phần giàu dưỡng chất Serum Biologique Recherche VG Tensil hỗ trợ tái tạo màng sợi của làn da ngay tức thì và kích thích trao đổi chất của tế bào giúp cho làn da trở nên săn chắc và đều màu hơn.',59, 4, 26),
( N'Serum Hỗ Trợ Phục Hồi Làm Sáng Da Biologique Recherche PIGM 400 30ml', 17, N'null', N'Pháp','20220501 10:00:09 AM', 2, N'Serum Hỗ Trợ Phục Hồi Làm Sáng Da Biologique Recherche PIGM 400 30ml là dòng sản phẩm đến từ thương hiệu Biologique Recherche nổi tiếng của Pháp. Với thành phần giàu dưỡng chất Serum Biologique Recherche PIGM 400 hỗ trợ giảm sự xuất hiện của các vết sắc tố, làm sáng và làm đều màu da.',59, 4, 26),
( N'Set Serum Estée Lauder Advanced Night Repair 3 Chai 30ml + 2 Serum 15ml', 15, N'null', N'Mỹ','20220501 10:00:09 AM', 2, N'Set Serum Estée Lauder Advanced Night Repair 3 Chai là tinh chất hỗ trợ da phục hồi ban đêm cho mọi loại da, tới từ thương hiệu Estee Lauder của Mỹ. Estee Lauder Advanced Night Repair mang đến làn da rạng rỡ, khỏe mạnh hơn khi thức dậy mỗi ngày.',151, 4, 26),
( N'Combo Sữa Rửa Mặt + Kem Chống Nắng Obagi 360 System Set 3 Món', 13, N'null', N'Mỹ','20220501 10:00:09 AM', 2, N'Combo Sữa Rửa Mặt + Kem Chống Nắng Obagi 360 System Set 3 Món là bộ sản phẩm đến từ thương hiệu Obagi nổi tiếng của Mỹ. Obagi 360 System hỗ trợ làm sạch, tẩy da chết, đồng thời dưỡng ẩm nhẹ nhàng và cải thiện các dấu hiệu tuổi tác trên da, giúp làn da luôn sạch sẽ, mềm mại và chắc khỏe tự nhiên.',308, 4, 25),
( N'Kem Dưỡng Mắt Origins Plantscription Anti-Aging Power Eye Cream 5ml', 6, N'null', N'Mỹ','20220501 10:00:09 AM',2, N'Kem Dưỡng Mắt Origins Plantscription Anti-Aging Power Eye Cream 5ml là sản phẩm dưỡng mắt mới của Origins được nghiên cứu từ các thành phần lành tính an toàn cho da, có khả năng phục hồi những lớp tế bào da sâu, cải thiện các dấu hiệu tuổi tác trên da như đốm nâu và nếp nhăn, giữ lại nét tươi sáng cho đôi mắt của bạn.',316, 4, 37),
( N'Serum Hỗ Trợ Cấp Ẩm Nuôi Dưỡng Da DBH Moisture B5 Serum 29ml', 6, N'null', N'Mỹ','20220501 10:00:09 AM', 2, N'Serum Hỗ Trợ Cấp Ẩm Nuôi Dưỡng Da DBH Moisture B5 Serum 29ml được nghiên cứu, phát triển bởi các chuyên gia DBH và ứng dụng công nghệ hiện đại từ Hoa Kỳ chứa thành phần cấp ẩm và giữ ẩm tốt như Hyaluronic Acid và Vitamin B5 thẩm thấu sâu vào da, hỗ trợ bổ sung và giữ nước để nuôi dưỡng các tế bào đang phát triển, khiến da khỏe mạnh, căng tràn sức sống.',141, 4, 26),
( N'Kem Dưỡng Mắt Origins Plantscription Anti-Aging Power Eye Cream 5ml', 6, N'null', N'Mỹ','20220501 10:00:09 AM', 2, N'Kem Dưỡng Mắt Origins Plantscription Anti-Aging Power Eye Cream 5ml là sản phẩm dưỡng mắt mới của Origins được nghiên cứu từ các thành phần lành tính an toàn cho da, có khả năng phục hồi những lớp tế bào da sâu, cải thiện các dấu hiệu tuổi tác trên da như đốm nâu và nếp nhăn, giữ lại nét tươi sáng cho đôi mắt của bạn.',252, 4, 37),
( N'Gel Chấm Mụn DBH Gel 5% BPO 28g', 8, N'null', N'Mỹ','20220501 10:00:09 AM', 2, N'Gel Chấm Mụn DBH Gel 5% BPO 28g được nghiên cứu, phát triển bởi các chuyên gia DBH và ứng dụng công nghệ hiện đại từ Hoa Kỳ loại bỏ sự tích tụ của những tế bào da chết và bã nhờn nằm sâu trong nang lông hình thành sư tắc nghẽn da gây nên mụn trứng cá, kháng khuẩn và giảm vi khuẩn gây mụn.',141, 4, 28),

INSERT INTO Products ( Name, Price, Material, MadeIn, CreateDate, Gender, Detail, BrandId, CategoryId, SubCategoryId) VALUES
( N'Giày MLB Play Ball Origin Mule New York Yankees 32SHS1111-50L Màu Đen Size 230', 18, N'Vải cao cấp', N'Hàn Quốc','20220501 10:00:09 AM', 2, N'Giày MLB Play Ball Origin Mule New York Yankees 32SHS1111-50L Màu Đen Size 230 là đôi giày Unisex cho cả nam và nữ, sản phẩm đến từ thương hiệu MLB nổi tiếng của Hàn Quốc với thiết kế trẻ trung, năng động. MLB Play Ball Origin Mule là đôi giày nằm trong chiến dịch kết hợp của MLB và nữ ca sĩ nổi tiếng Huyna.',287, 5, 54),
( N'Giày Sneaker MLB Big Ball Chunky A New York Yankees Màu Trắng Logo Đen Size 260', 20, N'da cao cấp', N'Hàn Quốc','20220501 10:00:09 AM', 2, N'Giày MLB Big Ball Chunky A New York Yankees Màu Trắng Logo Đen size 260 là đôi giày cao cấp với thiết kế hiện đại, thời trang đến từ thương hiệu MLB nổi tiếng của Hàn Quốc. MLB Big Ball Chunky A sẽ cho bạn trải nghiệm tuyệt vời nhất khi đi lên chân.',287, 5, 68),
( N'Giày MLB Big Ball Chunky P Boston Size 235', 20, N'da cao cấp', N'Hàn Quốc','20220501 10:00:09 AM', 2, N'Giày MLB Big Ball Chunky P Boston màu trắng họa tiết đỏ Size 235 là đôi giày Unisex cao cấp được làm bởi chất liệu đặc biệt, giày MLB tạo cảm giác thoải mái, êm chân khi đi. Với thiết kế độc đáo, phá cách, tạo nên sự trẻ trung, năng động cho người dùng.',287, 5, 68),
( N'Giày Gucci Ace Embroidered Sneaker White Leather With Bee Màu Trắng Size 39', 20, N'da cao cấp', N'Ý','20220501 10:00:09 AM', 2, N'Giày Gucci Ace Embroidered Sneaker White Leather With Bee màu trắng là mẫu giày sneakers cổ thấp của Gucci với họa tiết con ong thêu bằng chỉ vàng - biểu tượng của thương hiệu Gucci trên 3 sọc màu. Con ong trên giày là một họa tiết được giới thiệu lần đầu tiên trong trang phục may sẵn của Gucci vào những năm 1970.',188, 5, 68),
( N'Giày Thể Thao Puma Cruise Rider Silk Road Trainers Phối Màu', 13, N'Vải cao cấp + Da lộn', N'Đức','20220501 10:00:09 AM', 0, N'Giày Thể Thao Puma Cruise Rider Silk Road Trainers Phối Màu với thiết kế trẻ trung đến từ thương hiệu Puma nổi tiếng của Đức. Puma Cruise Rider Silk Road Trainers có kiểu dáng trẻ trung và hiện đại, được làm từ chất liệu cao cấp nên có độ bền cao và cực kỳ thoải mái.',321, 5, 54),
( N'Giày Louis Vuitton Sneaker LV Trainer Sneaker 1A9ZI6 Màu Trắng Vàng', 23, N'Vải cao cấp', N'Pháp','20220501 10:00:09 AM', 0, N'Giày Louis Vuitton Sneaker LV Trainer Sneaker 1A9ZI6 Màu Trắng Vàng được thương hiệu nổi tiếng thiết kế đẹp mắt, kiểu dáng thời trang Với đôi giày sang trọng này chắc chắn bạn sẽ trở nên nổi bật và cuốn hút hơn.',264, 5, 68),
( N'Giày Thể Thao Adidas Wmns Galaxy 5 Trace Maroon FW6124 Màu Đỏ Gạch Size 36', 15, N'Vải cao cấp', N'Đức','20220501 10:00:09 AM', 0, N'Giày Thể Thao Puma Cruise Rider Silk Road Trainers Phối Màu với thiết kế trẻ trung đến từ thương hiệu Puma nổi tiếng của Đức. Puma Cruise Rider Silk Road Trainers có kiểu dáng trẻ trung và hiện đại, được làm từ chất liệu cao cấp nên có độ bền cao và cực kỳ thoải mái.',33, 5, 54),
( N'Giày MLB Playball High Monogram Mesh New York Yankees 3ACVCMM2N-50IVS Màu Trắng', 15, N'Polyester / Cao su', N'Hàn Quốc','20220501 10:00:09 AM', 0, N'Giày Thể Thao Puma Cruise Rider Silk Road Trainers Phối Màu với thiết kế trẻ trung đến từ thương hiệu Puma nổi tiếng của Đức. Puma Cruise Rider Silk Road Trainers có kiểu dáng trẻ trung và hiện đại, được làm từ chất liệu cao cấp nên có độ bền cao và cực kỳ thoải mái.',287, 5, 57),
( N'Giày Thể Thao Nike Air Jordan 1 High Zoom CMFT – Black Chile Red Màu Đỏ Size 42', 20, N'Da cao cấp', N'Mỹ','20220501 10:00:09 AM', 0, N'Giày Thể Thao Nike Air Jordan 1 High Zoom CMFT – Black Chile Red Màu Đỏ được thiết kế mang nét thể thao phóng đại với phong cách trẻ trung, khỏe khoắn đặc trưng của thương hiệu Nike nổi tiếng của Mỹ. Nike Air Jordan 1 High Zoom CMFT hoàn hảo về chất lượng và vô cùng đẹp mắt chắc chắn bạn sẽ khó bỏ lỡ',294, 5, 54),
( N'Giày Nike Court Legacy White Desert Ochre CU4150-102 Màu Trắng', 20, N'Da cao cấp', N'Mỹ','20220501 10:00:09 AM', 0, N'Giày Nike Court Legacy White Desert Ochre CU4150-102 Màu Trắng là đôi giày thời trang có thiết kế trẻ trung, năng động đến từ thương hiệu Nike nổi tiếng của Mỹ. Giày Nike Court Legacy White Desert Ochre CU4150-102 được làm từ chất liệu cao cấp mang lại cảm giác thoải mái khi đi lên chân.',294, 5, 54)

select *  from Categories 















